package democrud.model;
// Generated Apr 1, 2017 3:45:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Systemuser generated by hbm2java
 */
public class Systemuser  implements java.io.Serializable {


     private Integer id;
     private int maNhanVien;
     private String ho;
     private String ten;
     private String matKhau;
     private int gioiTinh;
     private Date ngaySinh;
     private String noiSinh;
     private String diaChiThuongTru;
     private String diaChiTamTru;
     private String hinhAnh;
     private Set userdiplomas = new HashSet(0);

    public Systemuser() {
    }

	
    public Systemuser(int maNhanVien, String ho, String ten, int gioiTinh, Date ngaySinh, String noiSinh) {
        this.maNhanVien = maNhanVien;
        this.ho = ho;
        this.ten = ten;
        this.gioiTinh = gioiTinh;
        this.ngaySinh = ngaySinh;
        this.noiSinh = noiSinh;
    }
    public Systemuser(int maNhanVien, String ho, String ten, String matKhau, int gioiTinh, Date ngaySinh, String noiSinh, String diaChiThuongTru, String diaChiTamTru, String hinhAnh, Set userdiplomas) {
       this.maNhanVien = maNhanVien;
       this.ho = ho;
       this.ten = ten;
       this.matKhau = matKhau;
       this.gioiTinh = gioiTinh;
       this.ngaySinh = ngaySinh;
       this.noiSinh = noiSinh;
       this.diaChiThuongTru = diaChiThuongTru;
       this.diaChiTamTru = diaChiTamTru;
       this.hinhAnh = hinhAnh;
       this.userdiplomas = userdiplomas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(int maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public String getHo() {
        return this.ho;
    }
    
    public void setHo(String ho) {
        this.ho = ho;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public int getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(int gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getNoiSinh() {
        return this.noiSinh;
    }
    
    public void setNoiSinh(String noiSinh) {
        this.noiSinh = noiSinh;
    }
    public String getDiaChiThuongTru() {
        return this.diaChiThuongTru;
    }
    
    public void setDiaChiThuongTru(String diaChiThuongTru) {
        this.diaChiThuongTru = diaChiThuongTru;
    }
    public String getDiaChiTamTru() {
        return this.diaChiTamTru;
    }
    
    public void setDiaChiTamTru(String diaChiTamTru) {
        this.diaChiTamTru = diaChiTamTru;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Set getUserdiplomas() {
        return this.userdiplomas;
    }
    
    public void setUserdiplomas(Set userdiplomas) {
        this.userdiplomas = userdiplomas;
    }




}


