package democrud.model;
// Generated Apr 1, 2017 3:11:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userdiploma generated by hbm2java
 */
public class Userdiploma  implements java.io.Serializable {


     private int id;
     private Systemuser systemuser;
     private String tenBangCap;
     private Date ngayCap;
     private String noiCap;

    public Userdiploma() {
    }

	
    public Userdiploma(int id) {
        this.id = id;
    }
    public Userdiploma(int id, Systemuser systemuser, String tenBangCap, Date ngayCap, String noiCap) {
       this.id = id;
       this.systemuser = systemuser;
       this.tenBangCap = tenBangCap;
       this.ngayCap = ngayCap;
       this.noiCap = noiCap;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Systemuser getSystemuser() {
        return this.systemuser;
    }
    
    public void setSystemuser(Systemuser systemuser) {
        this.systemuser = systemuser;
    }
    public String getTenBangCap() {
        return this.tenBangCap;
    }
    
    public void setTenBangCap(String tenBangCap) {
        this.tenBangCap = tenBangCap;
    }
    public Date getNgayCap() {
        return this.ngayCap;
    }
    
    public void setNgayCap(Date ngayCap) {
        this.ngayCap = ngayCap;
    }
    public String getNoiCap() {
        return this.noiCap;
    }
    
    public void setNoiCap(String noiCap) {
        this.noiCap = noiCap;
    }




}


