package democrud.model;
// Generated Apr 1, 2017 3:45:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userdiploma generated by hbm2java
 */
public class Userdiploma  implements java.io.Serializable {


     private Integer id;
     private Systemuser systemuser;
     private String tenBangCap;
     private String noiCap;
     private Date ngayCap;

    public Userdiploma() {
    }

    public Userdiploma(Systemuser systemuser, String tenBangCap, String noiCap, Date ngayCap) {
       this.systemuser = systemuser;
       this.tenBangCap = tenBangCap;
       this.noiCap = noiCap;
       this.ngayCap = ngayCap;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Systemuser getSystemuser() {
        return this.systemuser;
    }
    
    public void setSystemuser(Systemuser systemuser) {
        this.systemuser = systemuser;
    }
    public String getTenBangCap() {
        return this.tenBangCap;
    }
    
    public void setTenBangCap(String tenBangCap) {
        this.tenBangCap = tenBangCap;
    }
    public String getNoiCap() {
        return this.noiCap;
    }
    
    public void setNoiCap(String noiCap) {
        this.noiCap = noiCap;
    }
    public Date getNgayCap() {
        return this.ngayCap;
    }
    
    public void setNgayCap(Date ngayCap) {
        this.ngayCap = ngayCap;
    }




}


